### ISSUE TITLE
masternode generated amount 0 and no balance update

### ISSUE THREAD

**Issue by vird** [friendshipCoin/friendshipcoin-core#3]
System info

    uname -a
    Linux 8bb7cfd5cc3b 4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
    git rev-parse HEAD
    cc4098fe68c1b0ee3a8ea3d1fb0b2fa505900ccf

masternode status

    friendshipcoind masternode status
    {
        "vin" : "CTxIn(COutPoint(83b9ca3eee, 0), scriptSig=)",
        "service" : "<myip>:58008",
        "status" : 1,
        "pubKeyMasternode" : "fJ1npEpLubtXRdXtvpnbMbvQfR6oFzZeuW",
        "notCapableReason" : ""
    }

Now see list transactions...

    friendshipcoind listtransactions
    [
        {
            "account" : "",
            "address" : "fXfvrvH2H5WQqnKHprCW9CYtnHXsZPCTWZ",
            "category" : "receive",
            "amount" : 14466.00000000,
            "confirmations" : 208,
            "bcconfirmations" : 208,
            "blockhash" : "1cb5c74885544f2363b361c11ccc66b608759ab5c7148c565f895ccd130032b5",
            "blockindex" : 2,
            "blocktime" : 1522314288,
            "txid" : "83b9ca3eeefc1195e115ad0a5d76986799568b921cdda952606dd2805b6ce6b8",
            "walletconflicts" : [
            ],
            "time" : 1522314288,
            "timereceived" : 1522314457
        },
        {
            "account" : "",
            "address" : "fXfvrvH2H5WQqnKHprCW9CYtnHXsZPCTWZ",
            "category" : "generate",
            "amount" : 0.00000000,
            "confirmations" : 138,
            "bcconfirmations" : 138,
            "generated" : true,
            "blockhash" : "85f485d2dff1556640ac335bd752e1c30c26faad0145e8ddea2f8ebcb198fb6a",
            "blockindex" : 1,
            "blocktime" : 1522323984,
            "txid" : "cabcdd9609bd14fab843d8ee0060d1a103fcc4887913cc0fbdffec89665ef758",
            "walletconflicts" : [
            ],
            "time" : 1522323984,
            "timereceived" : 1522323985
        },
        {
            "account" : "",
            "address" : "fXfvrvH2H5WQqnKHprCW9CYtnHXsZPCTWZ",
            "category" : "generate",
            "amount" : 0.00000000,
            "confirmations" : 94,
            "bcconfirmations" : 94,
            "generated" : true,
            "blockhash" : "bdcc5998bf0e9af70ec90451167a3f1c3a25e9e1e45d7628652391912e91ff0b",
            "blockindex" : 1,
            "blocktime" : 1522330432,
            "txid" : "5847a5f585ca910f30e7a092cf249199a1ffd42c9deaa28f7de3b497671cff6a",
            "walletconflicts" : [
            ],
            "time" : 1522330432,
            "timereceived" : 1522330432
        },
        {
            "account" : "",
            "address" : "fXfvrvH2H5WQqnKHprCW9CYtnHXsZPCTWZ",
            "category" : "immature",
            "amount" : 0.00000000,
            "confirmations" : 20,
            "bcconfirmations" : 20,
            "generated" : true,
            "blockhash" : "7aec022de158c824b9017ee150ab1603ee1b36973c18d9b24023ce4ad5df0144",
            "blockindex" : 1,
            "blocktime" : 1522340976,
            "txid" : "56173672be42e60769a2f39b04d58f6135bd3c775b9016cccdc08174fd5f8c23",
            "walletconflicts" : [
            ],
            "time" : 1522340976,
            "timereceived" : 1522340976
        }
    ]

why "amount" : 0.00000000, ?

    friendshipcoind listunspent
    [
        {
            "txid" : "5847a5f585ca910f30e7a092cf249199a1ffd42c9deaa28f7de3b497671cff6a",
            "vout" : 3,
            "address" : "fXfvrvH2H5WQqnKHprCW9CYtnHXsZPCTWZ",
            "account" : "",
            "scriptPubKey" : "76a914c0a5c4a3e6a8e36531223c2670df7846929de57688ac",
            "amount" : 100.00000000,
            "confirmations" : 96,
            "spendable" : true
        },
        {
            "txid" : "cabcdd9609bd14fab843d8ee0060d1a103fcc4887913cc0fbdffec89665ef758",
            "vout" : 2,
            "address" : "fXfvrvH2H5WQqnKHprCW9CYtnHXsZPCTWZ",
            "account" : "",
            "scriptPubKey" : "76a914c0a5c4a3e6a8e36531223c2670df7846929de57688ac",
            "amount" : 100.00000000,
            "confirmations" : 140,
            "spendable" : true
        }
    ]

Ok... seems i can just spent them...

    friendshipcoind getbalance
    14666.00000000

But there are not on balance... what?

**Comment by vidaru** [comment]
This is a display bug, the next release 0.1.0 will resolve this.

**Comment by vidaru** [comment]
See release #7
